### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by GioCirque**
- Updated package versions eliminating install issues with sodium
- Updated TypeScript reference and minor syntax adjustment to TypedEvents

### CODE REVIEW

**Comment by GioCirque** [comment]
This clear the sodium install error where it exits with code null.

**Comment by darvin** [comment]
needs to be merged, breaks the installation on all docker installs

**Comment by darvin** [comment]
*fixes the break

**Comment by eliottrobson** [comment]
I believe this would solve many problems people are facing (myself included) with plugins that depend on this package.

**Pull request closed without merging**
